### ISSUE TITLE
Unable to play videos within RTMPExploreX window

### ISSUE THREAD

**Issue by firehawk12** [andr3jx/RTMPExploreX#1]
I tried to play a video at crunchyroll.com - 
(random example - http://www.crunchyroll.com/bodacious-space-pirates/episode-25-the-pirates-council-begins-588952) - and the video does not play.  I see an "you have an old version of javascript or flash video player" before the message disappear and a blank window appears where the video player should be.

I've tried a few other sites just to be sure it wasn't me, but it looks like I am unable to play videos in the browser in order to get the rtmpe links.

Any help would be appreciated.

**Comment by andr3jx** [comment]
Hi! I answered here: http://stream-recorder.com/forum/showpost.php?p=48522&postcount=29
