### ISSUE TITLE
output is garbage

### ISSUE THREAD

**Issue by kinghat** [andr3jx/RTMPExploreX#3]
i get the video file but the output makes it so i cant skip ahead in the video using VLC and the video goes all potato.

**Comment by andr3jx** [comment]
Hello,
thanks for your comment. This issue seems not to be RTMPExploreX related. Try using an other player like GOM player. Moreover I don't update this program anymore, I recommend [RTMPDumpHelper](http://www.nirsoft.net/utils/rtmp_dump_helper.html).
